name: Run the Eigen tests

on: [pull_request]

env:
  BUILD_FOLDER: build

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/stimwalker
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/stimwalker
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\stimwalker
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: stimwalker
          environment-file: environment.yml
  
      - name: Print mamba info
        run: | 
          mamba info
          mamba list

      - name: Setup Linux dependencies
        run:   |
         sudo apt update
         sudo apt install libstdc++-11-dev
        if: matrix.label == 'linux-64'
        
      - name: Install extra common dependencies
        run: | 
          git submodule update --init --recursive

      - name: Build stimwalker UNIX
        run: |
          STIMWALKER_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/stimwalker
          mkdir -p $STIMWALKER_FOLDER/$BUILD_FOLDER
          cd $STIMWALKER_FOLDER/$BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
          make install -j${{ steps.cpu-cores.outputs.count }}
          cd $STIMWALKER_FOLDER
        if: matrix.label != 'win-64'

      - name: Run tests UNIX
        run: |
          STIMWALKER_FOLDER=`pwd`
          cd $STIMWALKER_FOLDER/$BUILD_FOLDER/test
          ./stimwalker_tests
          cd $STIMWALKER_FOLDER
        if: matrix.label != 'win-64'

      - name: Build stimwalker WINDOWS
        run: |
          STIMWALKER_FOLDER=`pwd`
          CONDA_ENV_PATH=$CONDA/envs/stimwalker
          mkdir -p $BUILD_FOLDER
          cd $BUILD_FOLDER
          cmake -G"Visual Studio 17 2022" -Ax64 -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
          cmake --build . --config Release --target install -j${{ steps.cpu-cores.outputs.count }}
          cd $STIMWALKER_FOLDER
        if: matrix.label == 'win-64'

      - name: Run tests WINDOWS
        run: |
          STIMWALKER_FOLDER=`pwd`
          cd $STIMWALKER_FOLDER/$BUILD_FOLDER/test
          cp Release/stimwalker_tests.exe .
          ./stimwalker_tests.exe
          cd $STIMWALKER_FOLDER
        if: matrix.label == 'win-64'
